services:
  store_manager:
    build: .
    container_name: store_manager 
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    networks:
      - labo08-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  mysql:
    image: mysql:8.4.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo08_db
      MYSQL_USER: labo08
      MYSQL_PASSWORD: labo08
    ports:
      - "3306:3306"
    networks:
      - labo08-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - labo08-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  krakend:
    image: devopsfaith/krakend:2.7
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
    networks:
      - labo08-network
    depends_on:
      store_manager:
        condition: service_started
      payments-api:
        condition: service_started
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: lab08-jaeger
    networks:
      - labo08-network
  mysql_payments:
    image: mysql:8.4.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo05_payments_db
      MYSQL_USER: labo05
      MYSQL_PASSWORD: labo05
    networks:
      - labo08-network
    volumes:
      - mysql_payments_data:/var/lib/mysql
      - ../ashleyguevarra_lab05_payement/db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
  payments-api:
    build: ../ashleyguevarra_lab05_payement
    container_name: lab08-payments-api
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=mysql_payments
      - DB_PORT=3306
      - DB_NAME=labo05_payments_db
      - DB_USER=labo05
      - DB_PASSWORD=labo05
      - KAFKA_HOST=kafka:29092
      - KAFKA_TOPIC=order-saga-events
      - KAFKA_GROUP_ID=payments-saga-group
    volumes:
      - ../ashleyguevarra_lab05_payement:/app
    networks:
      - labo08-network
    depends_on:
      mysql_payments:
        condition: service_healthy
      kafka:
        condition: service_healthy
      jaeger:
        condition: service_started
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    environment:
      CLUSTER_ID: "o0oqgfJkSRKy30HkVsAjBg"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - labo08-network

networks:
  labo08-network:
    external: true

volumes:
  mysql_data:
  mysql_payments_data:
  prometheus_data:
